### ISSUE TITLE
I got "Error: ExecutorServiceImpl::ProcessBatch() got oldAccInputHash too long, size=84"

### ISSUE THREAD

**Issue by egonspace** [0xPolygonHermez/zkevm-prover#215]
I'm building my own network with zkevm.

I ran a prover following this guide(https://github.com/iskraworld/zkevm-node/blob/develop/docs/production-setup.md),
but it raises the error `Error: ExecutorServiceImpl::ProcessBatch() got oldAccInputHash too long, size=84` when I link metamask to zkevm-node rpc endpoint and metamask requests `estimate_gas` to rpc endpoint.

Used prover config:
```
{
    "runProverServer": true,
    "runProverServerMock": true,
    "runProverClient": false,

    "runExecutorServer": true,
    "runExecutorClient": false,

    "runStateDBServer": true,
    "runStateDBTest": false,

    "runFile": false,
    "runFileFast": false,

    "runKeccakScriptGenerator": false,
    "runKeccakTest": false,
    "runStorageSMTest": false,
    "runBinarySMTest": false,
    "runMemAlignSMTest": false,
    "runStarkTest": false,

    "executeInParallel" : false,
    "useMainExecGenerated" : false,

    "proverServerPort": 50051,
    "proverServerMockPort": 50052,
    "proverClientPort": 50051,
    "proverServerMockTimeout": 60000000,

    "executorServerPort": 50071,
    "executorClientPort": 50071,
    "executorClientHost": "127.0.0.1",

    "stateDBServerPort": 50061,
    "stateDBURL": "local",

    "inputFile": "input_executor.json",
    "outputPath": "output",
    "romFile": "rom.json",
    "pilFile": "zkevm.pil.json",
    "cmPolsFile": "commit.bin",
    "constPolsFile": "basic.const",
    "constantsTreeFile": "basic.consttree",
    "scriptFile": "starkgen_bmscript.json",
    "starkFile_disabled": "stark.json",
    "verifierFile": "verifier.dat",
    "witnessFile_disabled": "witness.wtns",
    "starkVerifierFile": "starkverifier_0001.zkey",
    "publicFile": "public.json",
    "proofFile": "proof.json",
    "keccakScriptFile": "keccak_script.json",
    "keccakPolsFile_DISABLED": "keccak_pols.json",
    "keccakConnectionsFile": "keccak_connections.json",
    "storageRomFile": "storage_sm_rom.json", // -> this raises error, i fixed it to "config/scripts/storage_sm_rom.json"
    "storagePilFile": "storage.pil.json",
    "storagePolsFile": "storage.commit.bin",
    "memoryPilFile": "mem.pil.json",
    "memoryPolsFile": "mem.commit.bin",
    "binaryPilFile": "binary.pil.json",
    "binaryPolsFile": "binary.commit.bin",
    "binaryConstPolsFile": "binary.constants.bin",
    "starkInfoFile": "zkevm.starkinfo.json",

    "databaseURL": "postgresql://prover_user:prover_pass@...:5432/prover_db",
    "dbTableName": "state.merkletree",
    "dbAsyncWrite": false,
    "cleanerPollingPeriod": 600,
    "requestsPersistence": 3600
}
```

And I used the docker image(`hermeznetwork/zkevm-prover   develop   2b48b985fadd`)

And docker-compose.yml is
```
version: '3'

services:
  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:latest
    ports:
      - 50051:50051 # Prover Server
      - 50052:50052 # Prover Server Mock
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./prover-config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
```
