### ISSUE TITLE
Fatal error in prover when RPC calls to debug_traceTransaction

### ISSUE THREAD

**Issue by cg-polygon** [0xPolygonHermez/zkevm-prover#376]
## Problem
zkEVM-prover has a fatal error and has to restart when a `debug_traceTransaction` call is made to associated RPC

### Steps to reproduce

We enabled the debug endpoints on the RPC client with:
```
/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc --http.api eth,net,debug,zkevm,txpool,web3
```
Successfully start the node and then after waiting 30 seconds use curl to call `debug_traceTransaction`:
```
curl -H "Content-Type: application/json" -X POST --data '{"method": "debug_traceTransaction","params": ["0xb41d822cc765ba7bab1de5dfc05d6448a129866261aa820b609cf22ac66d049c"],"id": 42,"jsonrpc": "2.0"}' http://localhost:8545
```
This is returned from the server and the zkevm-prover restarts:
```
{"jsonrpc":"2.0","id":42,"error":{"code":-32000,"message":"failed to get trace"}}
```

## Error
This is the error that's returned on the zkevm-prover just before it restarts:
```
2023/03/26 01:52:11 --> PROVER_PROCESS_BATCH starting...
Prover::processBatch() timestamp=20230326_015211_304727 UUID=8fe1e43d-2ed1-495b-83e4-ae5a2c92f286
2023/03/26 01:52:11 --> MAIN_EXECUTOR_EXECUTE starting...
Error: FullTracer::onUpdateStorage() did not found deltaStorage of depth=1
CALL STACK
0: call=zkProver(_Z14printCallStackv+0x41) [0x565247663041]
1: call=zkProver(_Z11exitProcessv+0x11) [0x565247674ab1]
2: call=zkProver(_ZN6fork_210FullTracer15onUpdateStorageERNS_7ContextERKNS_10RomCommandE+0x1b6) [0x5652450ff256]
3: call=zkProver(_ZN6fork_210FullTracer11handleEventERNS_7ContextERKNS_10RomCommandE+0xfa) [0x5652450ff43a]
4: call=zkProver(_ZN6fork_211evalCommandERNS_7ContextERKNS_10RomCommandERNS_13CommandResultE+0xad9) [0x5652450cb109]
5: call=zkProver(_ZN6fork_212MainExecutor7executeER13ProverRequestRNS_14MainCommitPolsERNS_16MainExecRequiredE+0x1363b) [0x5652450ea8ab]
6: call=zkProver(_ZN8Executor13process_batchER13ProverRequest+0x40c) [0x56523aa408ec]
7: call=zkProver(_ZN6Prover12processBatchEP13ProverRequest+0x3c1) [0x56523e1d11b1]
8: call=zkProver(_ZN19ExecutorServiceImpl12ProcessBatchEPN9grpc_impl13ServerContextEPKN8executor2v119ProcessBatchRequestEPNS4_20ProcessBatchResponseE+0x362a) [0x56523aa7ea0a]
```

## Hardware
EC2 with 4 CPUs (Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz) and 32GB RAM

## Software Version
I'm using the newest [RC29 release](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.0.3-RC29) of zkevm-node. This docker image uses this prover: `hermeznetwork/zkevm-prover:5ad1821` 

## Configs
public.prover.config.json
```
{
    "runProverServer": false,
    "runProverServerMock": false,
    "runProverClient": false,

    "runExecutorServer": true,
    "runExecutorClient": false,
    "runExecutorClientMultithread": false,

    "runStateDBServer": true,
    "runStateDBTest": false,

    "runAggregatorServer": false,
    "runAggregatorClient": false,

    "runFileGenProof": false,
    "runFileGenBatchProof": false,
    "runFileGenAggregatedProof": false,
    "runFileGenFinalProof": false,
    "runFileProcessBatch": false,
    "runFileProcessBatchMultithread": false,

    "runKeccakScriptGenerator": false,
    "runKeccakTest": false,
    "runStorageSMTest": false,
    "runBinarySMTest": false,
    "runMemAlignSMTest": false,
    "runSHA256Test": false,
    "runBlakeTest": false,

    "executeInParallel": true,
    "useMainExecGenerated": false,
    "saveRequestToFile": false,
    "saveInputToFile": false,
    "saveDbReadsToFile": false,
    "saveDbReadsToFileOnChange": false,
    "saveOutputToFile": false,
    "saveResponseToFile": false,
    "loadDBToMemCache": false,
    "opcodeTracer": false,
    "logRemoteDbReads": false,
    "logExecutorServerResponses": false,

    "proverServerPort": 50051,
    "proverServerMockPort": 50052,
    "proverServerMockTimeout": 10000000,
    "proverClientPort": 50051,
    "proverClientHost": "127.0.0.1",

    "executorServerPort": 50071,
    "executorROMLineTraces": false,
    "executorClientPort": 50071,
    "executorClientHost": "127.0.0.1",

    "stateDBServerPort": 50061,
    "stateDBURL": "local",

    "aggregatorServerPort": 50081,
    "aggregatorClientPort": 50081,
    "aggregatorClientHost": "127.0.0.1",

    "inputFile": "input_executor.json",
    "outputPath": "output",
    "cmPolsFile_disabled": "zkevm.commit",
    "cmPolsFileC12a_disabled": "zkevm.c12a.commit",
    "cmPolsFileRecursive1_disabled": "zkevm.recursive1.commit",
    "constPolsFile": "zkevm.const",
    "constPolsC12aFile": "zkevm.c12a.const",
    "constPolsRecursive1File": "zkevm.recursive1.const",
    "mapConstPolsFile": false,
    "constantsTreeFile": "zkevm.consttree",
    "constantsTreeC12aFile": "zkevm.c12a.consttree",
    "constantsTreeRecursive1File": "zkevm.recursive1.consttree",
    "mapConstantsTreeFile": false,
    "starkFile": "zkevm.prove.json",
    "starkZkIn": "zkevm.proof.zkin.json",
    "starkZkInC12a":"zkevm.c12a.zkin.proof.json",
    "starkFileRecursive1": "zkevm.recursive1.proof.json",
    "verifierFile": "zkevm.verifier.dat",
    "verifierFileRecursive1": "zkevm.recursive1.verifier.dat",
    "witnessFile_disabled": "zkevm.witness.wtns",
    "witnessFileRecursive1": "zkevm.recursive1.witness.wtns",
    "execC12aFile": "zkevm.c12a.exec",
    "execRecursive1File": "zkevm.recursive1.exec",
    "starkVerifierFile": "zkevm.g16.0001.zkey",
    "publicStarkFile": "zkevm.public.json",
    "publicFile": "public.json",
    "proofFile": "proof.json",
    "keccakScriptFile": "keccak_script.json",
    "keccakPolsFile_DISABLED": "keccak_pols.json",
    "keccakConnectionsFile": "keccak_connections.json",
    "starkInfoFile": "zkevm.starkinfo.json",
    "starkInfoC12aFile": "zkevm.c12a.starkinfo.json",
    "starkInfoRecursive1File": "zkevm.recursive1.starkinfo.json",
    "databaseURL": "postgresql://prover_user:prover_pass@zkevm-state-db:5432/prover_db",
    "dbNodesTableName": "state.nodes",
    "dbProgramTableName": "state.program",
    "dbAsyncWrite": false,
    "dbMultiWrite": true,
    "dbMTCacheSize": 10240,
    "dbProgramCacheSize": 1024,
    "dbConnectionsPool": true,
    "dbNumberOfPoolConnections": 28,
    "cleanerPollingPeriod": 600,
    "requestsPersistence": 3600,
    "maxExecutorThreads": 20,
    "maxProverThreads": 8,
    "maxStateDBThreads": 8
}
```

public.node.config.toml
```
[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
FreeClaimGasLimit = 1500000
MaxTxBytesSize=30132
MaxTxDataBytesSize=30000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
        [Pool.DB]
        User = "pool_user"
        Password = "pool_password"
        Name = "pool_db"
        Host = "zkevm-pool-db"
        Port = "5432"
        EnableLog = false
        MaxConns = 200

[Etherman]
URL = "http://your.L1node.url"
L1ChainID = 5
PoEAddr = "0xa997cfD539E703921fD1e3Cf25b4c241a27a4c7A"
MaticAddr = "0x1319D23c2F7034F52Eb07399702B040bA278Ca49"
GlobalExitRootManagerAddr = "0x4d9427DCA0406358445bC0a8F88C26b704004f74"
MultiGasProvider = false
        [Etherman.Etherscan]
                ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = "https://rpc.public.zkevm-test.net/"
BroadcastURI = "public-grpc.zkevm-test.net:61090"
DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
EnableL2SuggestedGasPricePolling = false
        [RPC.WebSockets]
                Enabled = true
                Port = 8546

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 300
GenBlockNumber = 8572998

[MTClient]
URI = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = false
```

docker-compose.yml
```
version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-rpc:
    container_name: zkevm-rpc
    restart: unless-stopped
    depends_on:
      zkevm-pool-db:
        condition: service_healthy
      zkevm-state-db:
        condition: service_healthy
      zkevm-sync:
        condition: service_started
    image: hermeznetwork/zkevm-node:v0.0.3-RC29
    ports:
      - 8545:8545
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/public.node.config.toml:/app/config.toml
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc --http.api eth,net,debug,zkevm,txpool,web3"

  zkevm-sync:
    container_name: zkevm-sync
    restart: unless-stopped
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    image: hermeznetwork/zkevm-node:v0.0.3-RC29
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/public.node.config.toml:/app/config.toml
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components synchronizer"

  zkevm-state-db:
    container_name: zkevm-state-db
    restart: unless-stopped
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ${ZKEVM_NODE_STATEDB_DATA_DIR}:/var/lib/postgresql/data
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
      - "-c"
      - "config_file=/etc/postgresql.conf"

  zkevm-pool-db:
    container_name: zkevm-pool-db
    restart: unless-stopped
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    volumes:
      - ${ZKEVM_NODE_POOLDB_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-prover:
    container_name: zkevm-prover
    restart: unless-stopped
    image: hermeznetwork/zkevm-prover:3476ef0
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/public}/public.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
```
