### ISSUE TITLE
i can't for the life of me get this running for a pen test

### ISSUE THREAD

**Issue by visualbasic6** [0xPolygonHermez/zkevm-prover#887]
title.

the problem is that i'm seeing `FATAL   cmd/run.go:119  no contract code at given address` and process exits upon `docker-compose up`:

![Image](https://github.com/user-attachments/assets/05d3ceb4-b7ae-4ad6-878a-b9fe8e89b8df)

docker-compose.yml:
```
version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-rpc:
    container_name: zkevm-rpc
    depends_on:
      zkevm-pool-db:
        condition: service_healthy
      zkevm-state-db:
        condition: service_healthy
      zkevm-sync:
        condition: service_started
    image: zkevm-node
    ports:
      - 8545:8545
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-pool-db
      - ZKEVM_NODE_RPC_BROADCASTURI=zkevm-broadcast:61090
    volumes:
      - ./config/environments/public/public.node.config.toml:/app/config.toml
      - ./config/environments/public/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --cfg /app/config.toml --network custom --custom-network-file /app/genesis.json --components rpc"

  zkevm-sync:
    container_name: zkevm-sync
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    image: zkevm-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/environments/public/public.node.config.toml:/app/config.toml
      - ./config/environments/public/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --cfg /app/config.toml --network custom --custom-network-file /app/genesis.json --components synchronizer"

  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: [ "postgres", "-N", "500" ]

  zkevm-pool-db:
    container_name: zkevm-pool-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: [ "postgres", "-N", "500" ]

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:88f3835
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/environments/public/public.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
```

public.prover.config.json
```
{
    "runProverServer": false,
    "runProverServerMock": false,
    "runProverClient": false,

    "runExecutorServer": true,
    "runExecutorClient": false,
    "runExecutorClientMultithread": false,

    "runStateDBServer": true,
    "runStateDBTest": false,

    "runAggregatorServer": false,
    "runAggregatorClient": false,

    "runFileGenProof": false,
    "runFileGenBatchProof": false,
    "runFileGenAggregatedProof": false,
    "runFileGenFinalProof": false,
    "runFileProcessBatch": false,
    "runFileProcessBatchMultithread": false,

    "runKeccakScriptGenerator": false,
    "runKeccakTest": false,
    "runStorageSMTest": false,
    "runBinarySMTest": false,
    "runMemAlignSMTest": false,
    "runSHA256Test": false,
    "runBlakeTest": false,

    "executeInParallel": true,
    "useMainExecGenerated": false,
    "saveRequestToFile": false,
    "saveInputToFile": false,
    "saveDbReadsToFile": false,
    "saveDbReadsToFileOnChange": false,
    "saveOutputToFile": false,
    "saveResponseToFile": false,
    "loadDBToMemCache": true,
    "opcodeTracer": false,
    "logRemoteDbReads": false,
    "logExecutorServerResponses": false,

    "proverServerPort": 50051,
    "proverServerMockPort": 50052,
    "proverServerMockTimeout": 10000000,
    "proverClientPort": 50051,
    "proverClientHost": "127.0.0.1",

    "executorServerPort": 50071,
    "executorROMLineTraces": false,
    "executorClientPort": 50071,
    "executorClientHost": "127.0.0.1",

    "stateDBServerPort": 50061,
    "stateDBURL": "local",

    "aggregatorServerPort": 50081,
    "aggregatorClientPort": 50081,
    "aggregatorClientHost": "127.0.0.1",

    "inputFile": "input_executor.json",
    "outputPath": "output",
    "cmPolsFile_disabled": "zkevm.commit",
    "cmPolsFileC12a_disabled": "zkevm.c12a.commit",
    "cmPolsFileRecursive1_disabled": "zkevm.recursive1.commit",
    "constPolsFile": "zkevm.const",
    "constPolsC12aFile": "zkevm.c12a.const",
    "constPolsRecursive1File": "zkevm.recursive1.const",
    "mapConstPolsFile": false,
    "constantsTreeFile": "zkevm.consttree",
    "constantsTreeC12aFile": "zkevm.c12a.consttree",
    "constantsTreeRecursive1File": "zkevm.recursive1.consttree",
    "mapConstantsTreeFile": false,
    "starkFile": "zkevm.prove.json",
    "starkZkIn": "zkevm.proof.zkin.json",
    "starkZkInC12a":"zkevm.c12a.zkin.proof.json",
    "starkFileRecursive1": "zkevm.recursive1.proof.json",
    "verifierFile": "zkevm.verifier.dat",
    "verifierFileRecursive1": "zkevm.recursive1.verifier.dat",
    "witnessFile_disabled": "zkevm.witness.wtns",
    "witnessFileRecursive1": "zkevm.recursive1.witness.wtns",
    "execC12aFile": "zkevm.c12a.exec",
    "execRecursive1File": "zkevm.recursive1.exec",
    "starkVerifierFile": "zkevm.g16.0001.zkey",
    "publicStarkFile": "zkevm.public.json",
    "publicFile": "public.json",
    "proofFile": "proof.json",
    "keccakScriptFile": "keccak_script.json",
    "keccakPolsFile_DISABLED": "keccak_pols.json",
    "keccakConnectionsFile": "keccak_connections.json",
    "starkInfoFile": "zkevm.starkinfo.json",
    "starkInfoC12aFile": "zkevm.c12a.starkinfo.json",
    "starkInfoRecursive1File": "zkevm.recursive1.starkinfo.json",
    "databaseURL": "postgresql://prover_user:prover_pass@zkevm-state-db:5432/prover_db",
    "dbNodesTableName": "state.nodes",
    "dbProgramTableName": "state.program",
    "dbAsyncWrite": false,
    "cleanerPollingPeriod": 600,
    "requestsPersistence": 3600,
    "maxExecutorThreads": 20,
    "maxProverThreads": 8,
    "maxStateDBThreads": 8
}
```

public.node.config.toml
```
[Log]
Environment = "development"
Level = "debug"  # Changed to debug for more detailed logs
Outputs = ["stderr"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
FreeClaimGasLimit = 1500000
	[Pool.DB]
	User = "pool_user"
	Password = "pool_password"
	Name = "pool_db"
	Host = "zkevm-pool-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[Etherman]
URL = "https://sepolia.infura.io/v3/[redacted]"
L1ChainID = 11155111  # Sepolia chain ID
PoEAddr = "0xF6BEEe43cfc23F665279B7B896A88F427a815C98"  # L1 PolygonZkEVMBridge proxy
MaticAddr = "0x1cA296293A5538064bC6d13b0060F5cF3561f9f7"  # Test token (optional)
GlobalExitRootManagerAddr = "0x3DdF01dB5cFCf9915dC0b9D0940eA9cB869B8e6c"  # Updated L1 GlobalExitRootManager
MultiGasProvider = false
	[Etherman.Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = "https://public.zkevm-test.net:2083"
BroadcastURI = "zkevm-broadcast:61090"
DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
	[RPC.WebSockets]
		Enabled = true
		Port = 8546

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 100
GenBlockNumber = 3800000  # Updated to predate contract deployments

[L2GasPriceSuggester]
Type = "default"
DefaultGasPriceWei = 1000000000

[MTClient]
URI = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = false
```

i think i found a solid vuln in another zkevx integrated blockchain. i want to try to reproduce it on the real deal.

how do i run this w/ `docker-compose up`? the configuration is wrong

also seeing:
```
zkevm-pool-db     | 2025-03-23 19:31:45.935 UTC [656] FATAL:  role "root" does not exist
zkevm-state-db    | 2025-03-23 19:31:45.936 UTC [753] FATAL:  role "root" does not exist
```

because i put `root` at the top - but have since forgotten where that config file is located.

my brain is fried from trying to do this all day.
